MTToolBox: MTToolBox::AlgorithmBestBits< U > Class Template Reference
MTToolBox::AlgorithmBestBits< U > Class Template Reference
Algorithm which searches tempering parameters.
#include <AlgorithmBestBits.hpp>
Public Types
typedef temper_params< U > tempp
a class which keeps tempering parameters.
Public Member Functions
AlgorithmBestBits (int out_bit_length, const int shift_values[], int param_num, int limit_v)
~AlgorithmBestBits ()
A destructor.
int operator() (TemperingCalculatable< U > &rand, bool verbose=false)
Search tempering parameters.
bool isLSBTempering ()
Shows if tempering is from LSB.
Public Member Functions inherited from MTToolBox::AlgorithmTempering< U >
virtual bool isLSBTempering () const
Shows if searching tempering parameters is from LSBs.
Detailed Description
template<typename U>
class MTToolBox::AlgorithmBestBits< U >
Algorithm which searches tempering parameters.
An algorithm which searches tempering parameters which improve equi-distribution property of pseudo random number generator. This algorithm simulate the algorithm of Dynamic creator of Mersenne Twister.
Warning
If you could not get high dimension of equi-distribution after tempering using parameters got by this algorithm, you should consider changing the design of random number generation algorithm.
Template Parameters
U type of output of pseudo random number generator. Should be unsigned type.
Member Typedef Documentation
template<typename U > typedef temper_params<U> MTToolBox::AlgorithmBestBits< U >::tempp
a class which keeps tempering parameters.
Constructor & Destructor Documentation
template<typename U > MTToolBox::AlgorithmBestBits< U >::AlgorithmBestBits (int out_bit_length, const int shift_values[], int param_num, int limit_v) inline
Parameters
[in] out_bit_length Bit length of tempering parameters. usually, this equals to bit length of an output.
[in] shift_values Shift values corresponds to tempering parameter. Positive integers mean left shift and negative integers are not supported in current version.
[in] param_num Number of tempering parameters. In MTDC, this is two. Do not specify numbers over 7. Test is only done for 2. Greater numbers will consume huge CPU time and huge memories.
[in] limit_v limit of tempering bit. Each tempering parameters are searched for limit bit plus shift values of parameters following to the parameters. Greater limit will consume huge CPU time and huge memories.
template<typename U > MTToolBox::AlgorithmBestBits< U >::~AlgorithmBestBits () inline
A destructor.
Member Function Documentation
template<typename U > bool MTToolBox::AlgorithmBestBits< U >::isLSBTempering () inline
Shows if tempering is from LSB.
Returns
Always false.
template<typename U > int MTToolBox::AlgorithmBestBits< U >::operator() (TemperingCalculatable< U > & rand, bool verbose = false) inline virtual
Search tempering parameters.
Generate tempering parameters and Calculate dimension of equi-distribution and then choose tempering parameters which gives high dimension of equi-distribution. Searched tempering parameters are set to the pseudo random number generator.
Parameters
[in,out] rand A pseudo random number generator
[in] verbose A flag for printing redundant message
Returns
0 always zero
Implements MTToolBox::AlgorithmTempering< U >.
References MTToolBox::AbstractGenerator< U >::bitSize(), MTToolBox::TemperingCalculatable< U >::resetReverseOutput(), MTToolBox::TemperingCalculatable< U >::setTemperingPattern(), and MTToolBox::TemperingCalculatable< U >::setUpTempering().
The documentation for this class was generated from the following file:
AlgorithmBestBits.hpp