MTToolBox: MTToolBox::AlgorithmRecursionSearch< U, V > Class Template Reference
MTToolBox::AlgorithmRecursionSearch< U, V > Class Template Reference
Search parameters of state transition function of pseudo random number generator so that the characteristic polynomial of the function will have max degree and will be primitive.
#include <AlgorithmRecursionSearch.hpp>
Public Member Functions
AlgorithmRecursionSearch (RecursionSearchable< U, V > &generator, AbstractGenerator< V > &bg)
Constructor Size of internal state is supposed to be Mersenne Exponent.
AlgorithmRecursionSearch (RecursionSearchable< U, V > &generator, AbstractGenerator< V > &bg, const AlgorithmPrimitivity &primitivity)
Constructor Users can specify algorithm of primitivity judgement.
bool start (int try_count)
Start searching recursion parameters.
const std::string getParamString ()
Returns a string which shows parameters of pseudo random Call this method only after start() returns true.
const NTL::GF2X & getMinPoly () const
Returns a minimal polynomial of output of the pseudo random number generator.
long getCount () const
Returns tried count from the instance was created.
Detailed Description
template<typename U, typename V = U>
class MTToolBox::AlgorithmRecursionSearch< U, V >
Search parameters of state transition function of pseudo random number generator so that the characteristic polynomial of the function will have max degree and will be primitive.
Template Parameters
U Type of output of pseudo random number generator. Should be unsigned number.
V type of output of paramenter generator.
Constructor & Destructor Documentation
template<typename U , typename V = U> MTToolBox::AlgorithmRecursionSearch< U, V >::AlgorithmRecursionSearch (RecursionSearchable< U, V > & generator, AbstractGenerator< V > & bg) inline
Constructor Size of internal state is supposed to be Mersenne Exponent.
Parameters
[in,out] generator GF(2)-linear generator whose parameters will be searched. The generator will be changed.
[in,out] bg a generator used for generating numbers to make parameters. This generator is not need to be GF(2)-linear pseudo random number generator, for example, TinyMTDC in sample directory uses sequential counter.
References MTToolBox::isPrime(), and MTToolBox::MersennePrimitivity.
template<typename U , typename V = U> MTToolBox::AlgorithmRecursionSearch< U, V >::AlgorithmRecursionSearch (RecursionSearchable< U, V > & generator, AbstractGenerator< V > & bg, const AlgorithmPrimitivity & primitivity) inline
Constructor Users can specify algorithm of primitivity judgement.
Parameters
[in,out] generator GF(2)-linear generator whose parameters will be searched. The generator will be changed.
[in,out] bg a generator used for generating numbers to make parameters. This generator is not need to be GF(2)-linear pseudo random number generator, for example, TinyMTDC in sample directory uses sequential counter.
[in] primitivity A class to judge primitivity.
References MTToolBox::isPrime().
Member Function Documentation
template<typename U , typename V = U> long MTToolBox::AlgorithmRecursionSearch< U, V >::getCount () const inline
Returns tried count from the instance was created.
Returns
tried count from the instance was created.
template<typename U , typename V = U> const NTL::GF2X& MTToolBox::AlgorithmRecursionSearch< U, V >::getMinPoly () const inline
Returns a minimal polynomial of output of the pseudo random number generator.
Call this method only after start() returns true.
Returns
a minimal polynomial
template<typename U , typename V = U> const std::string MTToolBox::AlgorithmRecursionSearch< U, V >::getParamString () inline
Returns a string which shows parameters of pseudo random Call this method only after start() returns true.
Returns
String which shows parameters of pseudo random number generator.
template<typename U , typename V = U> bool MTToolBox::AlgorithmRecursionSearch< U, V >::start (int try_count) inline
Start searching recursion parameters.
the generator make parameters randomly (RecursionSearchable.setUpParam()),
calculate minimal polynomial of the generator,
check if the polynomial has max possible degree and is primitive.
if check OK, then return true.
else repeat from 1.
If repeat count is over try_count, then return false.
Parameters
[in] try_count maximum count of try
Returns
true when proper minimal polynomial is gotten.
References MTToolBox::isPrime(), and MTToolBox::minpoly().
The documentation for this class was generated from the following file:
AlgorithmRecursionSearch.hpp