MTToolBox: MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G > Class Template Reference
MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G > Class Template Reference
#include <AlgorithmReducibleRT.hpp>
Public Member Functions
AlgorithmReducibleRecursionAndTempering (AbstractGenerator< U > &bg)
Constructor.
bool search (G &rg, AlgorithmTempering< U > &st1, AlgorithmTempering< U > &st2, bool verbose=false, std::ostream &os=std::cout, bool no_lsb=false)
Search parameters for state transition function and parameters for tempering.
bool search (TemperingCalculatable< U > &rg, AlgorithmTempering< U > &st, bool verbose=false, std::ostream &os=std::cout)
Simple wrapper for users who want to search tempering parameter only from MSB.
int getDelta ()
returns sum of d(v)s, which are difference between k(v) and theoretical upper bound.
const NTL::GF2X & getIrreducibleFactor ()
Returns irreducible factor with mexp degree of characteristic polynomial of state transition function.
U getParity () const
Returns a period certification vector (parity check vector)
Detailed Description
template<typename U, typename G>
class MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >
Search parameters of state transion function of reducible pseudo random number generator.
Search tempering parameters to improve dimension of equi-distribution of output of pseudo random number generator.
Template Parameters
U Type of output of pseudo random number.
G Type of pseudo random number generator. generator. Should be unsigned number.
Constructor & Destructor Documentation
template<typename U , typename G > MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::AlgorithmReducibleRecursionAndTempering (AbstractGenerator< U > & bg) inline
Constructor.
Parameters
bg a generator used for generating numbers to make parameters. This generator is not need to be GF(2)-linear pseudo random number generator, for example, TinyMTDC in sample directory uses sequential counter.
Member Function Documentation
template<typename U , typename G > int MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::getDelta () inline
returns sum of d(v)s, which are difference between k(v) and theoretical upper bound.
Returns
sum of d(v)s.
template<typename U , typename G > const NTL::GF2X& MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::getIrreducibleFactor () inline
Returns irreducible factor with mexp degree of characteristic polynomial of state transition function.
Returns
irreducible factor with mexp degree of characteristic polynomial of state transition function.
template<typename U , typename G > U MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::getParity () const inline
Returns a period certification vector (parity check vector)
Returns
a period certification vector (parity check vector)
template<typename U , typename G > bool MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::search (G & rg, AlgorithmTempering< U > & st1, AlgorithmTempering< U > & st2, bool verbose = false, std::ostream & os = std::cout, bool no_lsb = false) inline
Search parameters for state transition function and parameters for tempering.
Parameters
rg GF(2)-linear pseudo random number generator whose parameters are to be searched.
st1 Algorithm for searching tempering parameters.
st2 Algorithm for searching tempering parameters from LSB.
verbose if true redundant messages will be outputed.
os output stream for redundant messages.
no_lsb if true, st2 will not be used.
Returns
false if no tempering parameters which gives proper state transition function are found.
References MTToolBox::annihilate(), MTToolBox::calcCharacteristicPolynomial(), MTToolBox::AlgorithmEquidistribution< U, V >::get_all_equidist(), MTToolBox::AlgorithmTempering< U, V >::isLSBTempering(), and MTToolBox::AlgorithmCalculateParity< U, G >::searchParity().
Referenced by MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::search().
template<typename U , typename G > bool MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::search (TemperingCalculatable< U > & rg, AlgorithmTempering< U > & st, bool verbose = false, std::ostream & os = std::cout) inline
Simple wrapper for users who want to search tempering parameter only from MSB.
Parameters for state transition function are searched.
Parameters
rg GF(2)-linear pseudo random number generator whose parameters are to be searched.
st Algorithm for searching tempering parameters.
verbose if true redundant messages will be outputed.
os output stream for redundant messages.
Returns
false if no tempering parameters which gives proper state transition function are found.
References MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::search().
The documentation for this class was generated from the following file:
AlgorithmReducibleRT.hpp