MTToolBox: MTToolBox::AlgorithmCalculateParity< U, G > Class Template Reference
MTToolBox::AlgorithmCalculateParity< U, G > Class Template Reference
Calculate the parity check vector of reducible generator.
#include <AlgorithmCalculateParity.hpp>
Public Member Functions
U searchParity (G &g, const NTL::GF2X &f)
calculate the basis of subspace annihilated by q, and get the period certification vector (parity vector).
Detailed Description
template<typename U, typename G>
class MTToolBox::AlgorithmCalculateParity< U, G >
Calculate the parity check vector of reducible generator.
Template Parameters
U type of output of generator
G generator
Member Function Documentation
template<typename U, typename G> U MTToolBox::AlgorithmCalculateParity< U, G >::searchParity (G & g, const NTL::GF2X & f) inline
calculate the basis of subspace annihilated by q, and get the period certification vector (parity vector).
Parameters
[in] g reducible generator
[in] f large irreducible factor of characteristic polynomial.
Returns
the period certification vector (parity vector)
References MTToolBox::isZero(), and MTToolBox::setZero().
Referenced by MTToolBox::AlgorithmReducibleRecursionAndTempering< U, G >::search().
The documentation for this class was generated from the following file:
AlgorithmCalculateParity.hpp