MTToolBox: MTToolBox::TemperingCalculatable< U, V > Class Template Reference
MTToolBox::TemperingCalculatable< U, V > Class Template Reference abstract
Users can search tempering parameters by making GF(2)-linear pseudo random generator class which inherits from this class.
#include <TemperingCalculatable.hpp>
Public Member Functions
virtual ~TemperingCalculatable ()
Virtual destructor (always required)
virtual void setTemperingPattern (U mask, U pattern, int index)=0
Set tempering parameters.
virtual void setUpTempering ()=0
If preparing is needed before generation, here is the place to prepare tempering parameters.
virtual void setReverseOutput ()=0
Changes bit order of output.
virtual void resetReverseOutput ()=0
Reset bit order of output.
virtual bool isReverseOutput ()=0
Shows if bit order is reversed.
Public Member Functions inherited from MTToolBox::EquidistributionCalculatable< U, V >
virtual ~EquidistributionCalculatable ()
Virtual destructor (always required)
virtual EquidistributionCalculatable< U, V > * clone () const =0
Return copy of myself.
virtual U generate (int outBitLen)=0
output outBitLen from MSB.
virtual void add (EquidistributionCalculatable< U, V > &that)=0
Add internal state of GF(2)-linear pseudo random number generators.
virtual void setZero ()=0
Set all zero to internal state.
virtual bool isZero () const =0
Check if bits in internal state are all zero.
Public Member Functions inherited from MTToolBox::RecursionSearchable< U, V >
virtual ~RecursionSearchable ()
Virtual destructor (always required)
virtual void setUpParam (AbstractGenerator< V > &generator)=0
Users should set parameters for their generator when this method is called.
virtual const std::string getHeaderString ()=0
Returns header string of parameters.
virtual const std::string getParamString ()=0
Returns string expression of parameters.
Public Member Functions inherited from MTToolBox::AbstractGenerator< U >
virtual ~AbstractGenerator ()
Virtual destructor (always required)
virtual U generate ()=0
transit current internal state to next state and output a pseudo random number.
virtual void seed (U value)=0
initialize internal state
virtual int bitSize () const =0
Return bit size of internal state, i.e dimension of GF(2)-vector space.
Detailed Description
template<typename U, typename V = U>
class MTToolBox::TemperingCalculatable< U, V >
Users can search tempering parameters by making GF(2)-linear pseudo random generator class which inherits from this class.
Template Parameters
U type of output of pseudo random number generator
U type of output of pseudo random number generator
V type of output of parameter generator
Constructor & Destructor Documentation
template<typename U, typename V = U> virtual MTToolBox::TemperingCalculatable< U, V >::~TemperingCalculatable () inline virtual
Virtual destructor (always required)
Member Function Documentation
template<typename U, typename V = U> virtual bool MTToolBox::TemperingCalculatable< U, V >::isReverseOutput () pure virtual
Shows if bit order is reversed.
Returns
true if bit order id reversed
template<typename U, typename V = U> virtual void MTToolBox::TemperingCalculatable< U, V >::resetReverseOutput () pure virtual
Reset bit order of output.
Referenced by MTToolBox::AlgorithmPartialBitPattern< U, V, bit_len, param_num, try_bit_len, step, lsb >::operator()(), MTToolBox::AlgorithmBestBits< U, V >::operator()(), and MTToolBox::AlgorithmRecursionAndTempering< U, V >::search().
template<typename U, typename V = U> virtual void MTToolBox::TemperingCalculatable< U, V >::setReverseOutput () pure virtual
Changes bit order of output.
MSB of output becomes LSB of output. This is useful to calculate lower bit equi-distribution.
Referenced by MTToolBox::AlgorithmPartialBitPattern< U, V, bit_len, param_num, try_bit_len, step, lsb >::operator()(), and MTToolBox::AlgorithmRecursionAndTempering< U, V >::search().
template<typename U, typename V = U> virtual void MTToolBox::TemperingCalculatable< U, V >::setTemperingPattern (U mask, U pattern, int index) pure virtual
Set tempering parameters.
Parameters
[in] mask Shows which part of pattern should be set to parameter.
[in] pattern a part of pattern set to tempering parameter
[in] index index of tempering parameters.
Referenced by MTToolBox::AlgorithmBestBits< U, V >::operator()().
template<typename U, typename V = U> virtual void MTToolBox::TemperingCalculatable< U, V >::setUpTempering () pure virtual
If preparing is needed before generation, here is the place to prepare tempering parameters.
Referenced by MTToolBox::AlgorithmBestBits< U, V >::operator()().
The documentation for this class was generated from the following file:
TemperingCalculatable.hpp