MTToolBox: MTToolBox::MersenneTwister Class Reference
MTToolBox::MersenneTwister Class Reference
Mersenne Twister pseudo random number generator.
#include <MersenneTwister.hpp>
Public Member Functions
MersenneTwister ()
Constructor without arguments.
MersenneTwister (uint32_t value)
Constructor with a integer seed.
MersenneTwister (const std::string &value)
Constructor with a string seed.
MersenneTwister (const uint32_t *value, int size)
Constructor with an array of integer.
~MersenneTwister ()
Destructor.
void seed (uint32_t value)
Initialization by 32-bit integer.
void seed (const std::string &value)
Initialization by a string.
void seed (const uint32_t *value, int key_length)
Initialization by an array of unsigned integers.
template<class T >
void seed_array (const T *value, int key_length)
Initialization by an array of T type.
uint32_t generate ()
Generates pseudo random number.
uint32_t next ()
Generates pseudo random number.
int bitSize () const
Returns 19937, which is size of internal state.
Public Member Functions inherited from MTToolBox::AbstractGenerator< uint32_t >
virtual ~AbstractGenerator ()
Virtual destructor (always required)
Detailed Description
Mersenne Twister pseudo random number generator.
Constructor & Destructor Documentation
MTToolBox::MersenneTwister::MersenneTwister () inline
Constructor without arguments.
References seed().
MTToolBox::MersenneTwister::MersenneTwister (uint32_t value) inline
Constructor with a integer seed.
Parameters
[in] value Seed of initialization
References seed().
MTToolBox::MersenneTwister::MersenneTwister (const std::string & value) inline
Constructor with a string seed.
Parameters
[in] value Seed of initialization
References seed().
MTToolBox::MersenneTwister::MersenneTwister (const uint32_t * value, int size) inline
Constructor with an array of integer.
Parameters
[in] value Seed of initialization
[in] size length of value
References seed().
MTToolBox::MersenneTwister::~MersenneTwister () inline
Destructor.
Member Function Documentation
int MTToolBox::MersenneTwister::bitSize () const inline virtual
Returns 19937, which is size of internal state.
Returns
Always 19937
Implements MTToolBox::AbstractGenerator< uint32_t >.
uint32_t MTToolBox::MersenneTwister::generate () inline virtual
Generates pseudo random number.
Returns
a 32-bit unsigned integer
Implements MTToolBox::AbstractGenerator< uint32_t >.
References next().
uint32_t MTToolBox::MersenneTwister::next () inline
Generates pseudo random number.
Returns
a 32-bit unsigned integer
Referenced by generate().
void MTToolBox::MersenneTwister::seed (uint32_t value) inline virtual
Initialization by 32-bit integer.
Parameters
[in] value Seed of initialization
Implements MTToolBox::AbstractGenerator< uint32_t >.
Referenced by MersenneTwister(), and seed_array().
void MTToolBox::MersenneTwister::seed (const std::string & value) inline
Initialization by a string.
Parameters
[in] value Seed of initialization
void MTToolBox::MersenneTwister::seed (const uint32_t * value, int key_length) inline
Initialization by an array of unsigned integers.
Parameters
[in] value Seed of initialization
[in] key_length Length of value
template<class T > void MTToolBox::MersenneTwister::seed_array (const T * value, int key_length) inline
Initialization by an array of T type.
Template Parameters
T type of element of value
Parameters
[in] value Seed of initialization
key_length Length of value
References seed().
The documentation for this class was generated from the following file:
MersenneTwister.hpp