MTToolBox: MTToolBox::Sequential< T > Class Template Reference
MTToolBox::Sequential< T > Class Template Reference
Counting down number generator.
#include <Sequential.hpp>
Public Member Functions
Sequential ()
Constructor.
Sequential (T p_mask)
Constructor with mask.
Sequential (T p_mask, T seed)
Sequential (Sequential< T > &src)
void seed (T value)
initialize internal state
void reseed (T seed)
T generate ()
transit current internal state to next state and output a pseudo random number.
T next ()
int bitSize () const
Return bit size of internal state, i.e dimension of GF(2)-vector space.
Public Member Functions inherited from MTToolBox::AbstractGenerator< T >
virtual ~AbstractGenerator ()
Virtual destructor (always required)
Detailed Description
template<typename T>
class MTToolBox::Sequential< T >
Counting down number generator.
Template Parameters
T type of output, should be integer type
Constructor & Destructor Documentation
template<typename T> MTToolBox::Sequential< T >::Sequential () inline
Constructor.
template<typename T> MTToolBox::Sequential< T >::Sequential (T p_mask) inline
Constructor with mask.
Parameters
[in] p_mask p_mask and internal counter are exclusively or-ed when output time.
template<typename T> MTToolBox::Sequential< T >::Sequential (T p_mask, T seed) inline
References MTToolBox::Sequential< T >::seed().
template<typename T> MTToolBox::Sequential< T >::Sequential (Sequential< T > & src) inline
Member Function Documentation
template<typename T> int MTToolBox::Sequential< T >::bitSize () const inline virtual
Return bit size of internal state, i.e dimension of GF(2)-vector space.
It will be Mersenne Exponent, when generator use incomplete array, like Mersenne Twister.
Returns
bit size of internal state
Implements MTToolBox::AbstractGenerator< T >.
template<typename T> T MTToolBox::Sequential< T >::generate () inline virtual
transit current internal state to next state and output a pseudo random number.
Returns
a pseudo random number
Implements MTToolBox::AbstractGenerator< T >.
References MTToolBox::Sequential< T >::next().
template<typename T> T MTToolBox::Sequential< T >::next () inline
Referenced by MTToolBox::Sequential< T >::generate().
template<typename T> void MTToolBox::Sequential< T >::reseed (T seed) inline
References MTToolBox::Sequential< T >::seed().
Referenced by MTToolBox::Sequential< T >::seed().
template<typename T> void MTToolBox::Sequential< T >::seed (T value) inline virtual
initialize internal state
Initialization function does not need to be a GF(2)-linear function, non-GF(2)-linear function will be suitable. But as far as MTToolBox concerned, initialization only need to assure that the internal state is not zero. When generator use incomplete array, like Mersenne Twister, really used part of array should be set non-zero.
Parameters
[in] value seed of initialization
Implements MTToolBox::AbstractGenerator< T >.
References MTToolBox::Sequential< T >::reseed().
Referenced by MTToolBox::Sequential< T >::reseed(), and MTToolBox::Sequential< T >::Sequential().
The documentation for this class was generated from the following file:
Sequential.hpp