# scons construct file
# see http://www.scons.org/
#
# This file is called by top level SConstruct file.

target = 'MTToolBox'
include_path = ['../include', '.']
env = Environment(CPPFLAGS=['-Wall', '-g', '-O3', '-Wextra',
                            '-D__STDC_CONSTANT_MACROS',
                            '-D__STDC_FORMAT_MACROS'])
env.Append(CPPPATH=include_path)
lib = env.StaticLibrary(target, ['period.cpp','AlgorithmPrimitivity.cpp'])
